### ISSUE TITLE
драконы_начало

### ISSUE THREAD

**Issue by leraved** [Geelay/Kak_nibud_kruto#4]
@antosha417, начинаем обсуждать драконов
cd62092d122f3e51ea9834128caf7358d3207558

**Comment by KTune** [comment]
[согласны?](https://github.com/Geelay/Kak_nibud_kruto/commit/ece4fa27ae85e2e46efff7d5a0d57f3baaea68eb)
@antosha417

**Comment by leraved** [comment]
почему бы и нет

**Comment by antosha417** [comment]
Непонятные файлы нужно удалить с гитхаба
